let
     Source = Date.StartOfYear(Date.AddYears(DateTime.LocalNow(),-1)),
     Custom= List.Dates(Date.From(Source), 1+ Duration.Days( Duration.From(Date.EndOfYear(DateTime.LocalNow()) - Source)), #duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Custom, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), type number),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), type number),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Month Name", "Day Name", each Date.DayOfWeekName([Date]), type text),
    #"Added Custom" = Table.AddColumn(#"Inserted Day Name", "Custom", each if Date.IsInCurrentMonth([Date]) then 1 else 0),
    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom",{{"Custom", "MTD"}}),
    #"Added Custom1" = Table.AddColumn(#"Renamed Columns1", "YTD", each if Date.IsInYearToDate([Date]) then 1 else 0),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "LYTD", each if Date.IsInYearToDate(Date.AddYears([Date],+1)) then 1 else 0),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "LYMTD", each if (Date.IsInCurrentMonth(Date.AddYears([Date],+1)) and Date.IsInYearToDate(Date.AddYears([Date],+1))) then 1 else 0),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Day", each if DateTime.Date([Date]) = DateTime.Date(DateTime.LocalNow()) then 1 else 0),
    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "LY Day", each if DateTime.Date(Date.AddYears([Date],+1)) = DateTime.Date(DateTime.LocalNow()) then 1 else 0),
    #"Inserted Quarter" = Table.AddColumn(#"Added Custom5", "Quarter", each Date.QuarterOfYear([Date]), type number)
in
    #"Inserted Quarter"
