let

     Source = Date.StartOfYear(Date.AddYears(DateTime.LocalNow(),-1)),

     Custom= List.Dates(Date.From(Source), 1+ Duration.Days( Duration.From(Date.EndOfYear(DateTime.LocalNow()) - Source)), #duration(1,0,0,0)),

    #"Converted to Table" = Table.FromList(Custom, Splitter.SplitByNothing(), null, null, ExtraValues.Error),

    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),

    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), type number),

    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), type number),

    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),

    #"Inserted Day Name" = Table.AddColumn(#"Inserted Month Name", "Day Name", each Date.DayOfWeekName([Date]), type text),
 #"Changed Type" = Table.TransformColumnTypes(#"Inserted Day Name",{{"Date", type date}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "LYTD", each if Date.IsInYearToDate(Date.AddYears([Date],+1)) then 1 else 0),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"LYTD", Int64.Type}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "LY MTD", each if (Date.IsInCurrentMonth(Date.AddYears([Date],+1)) and Date.IsInYearToDate(Date.AddYears([Date],+1))) then 1 else 0),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"LY MTD", Int64.Type}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "YTD", each if Date.IsInYearToDate([Date]) then 1 else 0),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "MTD", each if (Date.IsInCurrentMonth([Date]) and Date.IsInYearToDate([Date])) then 1 else 0),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"MTD", Int64.Type}, {"YTD", Int64.Type}}),
    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Today", each if DateTime.Date([Date]) = DateTime.Date(DateTime.LocalNow()) then 1 else 0),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom4",{{"Today", Int64.Type}}),
    #"Added Custom5" = Table.AddColumn(#"Changed Type4", "Today LY", each if DateTime.Date(Date.AddYears([Date],+1)) = DateTime.Date(DateTime.LocalNow()) then 1 else 0),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Today LY", Int64.Type}})
in
    #"Changed Type5"
